In [1]:
import numpy as np
large_arr = np.random.rand(150)


In [2]:
int(0.05*len(large_arr))

7

상위 5% 의 값들을 출력하기 

In [3]:
np.sort(large_arr)[::-1][:int(0.05*len(large_arr))+1]

array([ 0.9937748 ,  0.97540448,  0.9685626 ,  0.95806579,  0.95474509,
        0.95368476,  0.95044155,  0.94845   ])

In [4]:
np.sort(large_arr)[::-1][7] #상위 5%의 경계에 걸쳐 있는 값

0.94845000145046987

배열의 유일한 값만 출력하기

In [5]:
names = np.array(["charles","kilho","hayoung","charles","kilho","hayoung","superior"])

In [6]:
ints = np.array([3,3,2,1,1,4,4])

In [7]:
np.unique(names)

array(['charles', 'hayoung', 'kilho', 'superior'], 
      dtype='<U8')

# Practice

by ratings.dat

rating 파일을 불러와서 데이터 정제하기(delimiter : 구분자)

In [8]:
data = np.loadtxt("ratings.dat",delimiter = "::",dtype=np.int64)

In [9]:
data[:5,:]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]], dtype=int64)

모든 공공데이터는 .dat 형식으로 되어있다.

In [10]:
data.shape #데이터의 크기 확인하기

(1000209, 4)

모든 행의 열(index:2)의 평균 구하기

In [11]:
mean_rating = data[:,2].mean()
mean_rating

3.5815644530293169

중복된 행 제거하기

In [12]:
user_ids=np.unique(data[:,0])
user_ids

array([   1,    2,    3, ..., 6038, 6039, 6040], dtype=int64)

In [13]:
user_ids.shape

(6040,)

이상 위 과정은 데이터 전처리 과정으로 결측치를 제거하기 위한 중요한 절차이다. 

id별로 세 번째 열(index:2)의 평균을 구하기

In [14]:
mean_rating_by_user_list = []
for user_id in user_ids:
    data_for_user=data[data[:,0]==user_id,:]
    mean_rating_for_user=data_for_user[:,2].mean()
    mean_rating_by_user_list.append([user_id,mean_rating_for_user])

In [15]:
mean_rating_by_user_list[:10]

[[1, 4.1886792452830193],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.1904761904761907],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.8848920863309351],
 [9, 3.7358490566037736],
 [10, 4.1147132169576057]]

실수로의 캐스팅(아직 못함)

In [25]:
np.array(mean_rating_by_user_list[:10],dtype = np.float64)

array([[  1.        ,   4.18867925],
       [  2.        ,   3.71317829],
       [  3.        ,   3.90196078],
       [  4.        ,   4.19047619],
       [  5.        ,   3.14646465],
       [  6.        ,   3.90140845],
       [  7.        ,   4.32258065],
       [  8.        ,   3.88489209],
       [  9.        ,   3.73584906],
       [ 10.        ,   4.11471322]])