# Library, numpy

In [2]:
import numpy as np

In [3]:
data1 = [6,7.5,8,0,1]

.array

In [4]:
#
arr1 =  np.array(data1)

In [6]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [14]:
data2 = [[1,2,3],[4,5,6]]

.shape

In [ ]:
#크기 확인 .shape
arr1.shape

In [61]:
arr2 = np.array(data2)

In [62]:
arr2.shape

(2, 3)

모든 성분을 0으로 정의

In [34]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

모든 성분을 1로 정의

In [35]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

0부터 1씩 증가하며 성분 채우기

In [106]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Data Type 의 정의(Data Type 을 따로 명시해주지 않으면 자동으로 인식한다.) 

In [26]:
arr1.dtype

dtype('float64')

In [28]:
arr2.dtype

dtype('int32')

In [108]:
arr=np.array([1,2,3,4,5],dtype=np.int64)
arr.dtype

dtype('int64')

.astype

In [293]:
#타입변경
np.array([1,2,3,4,5]).astype(float)

array([ 1.,  2.,  3.,  4.,  5.])

2차원 배열

In [39]:
arr12 = np.array([[1,2,3,4],[5,6,7,8]],dtype = np.float64)

배열의 연산

In [44]:
#배열 사이에 연산을 할 때에는 규칙이 적용된다.(행렬의 크기가 같아야 한다. )

arr22 = np.array([[9,10,11,12],[13,14,15,16]], dtype = np.float64)
arr12 + arr22

array([[ 10.,  12.,  14.,  16.],
       [ 18.,  20.,  22.,  24.]])

In [47]:
arr1*2

array([ 12.,  15.,  16.,   0.,   2.])

In [49]:
arr1**0.05

array([ 1.09372355,  1.10599474,  1.10956947,  0.        ,  1.        ])

In [52]:
1/arr12 #divide/0 오류가 생길 수 있음에 주의한다. 

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ]])

In [55]:
float_arr = arr.astype(np.float)

In [56]:
float_arr

array([ 1.,  2.,  3.,  4.,  5.])

In [59]:
arr = np.arange(10)

In [60]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
# 모든 원소 출력
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
#특정 순서
arr[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
arr[3:5]

array([3, 4])

2차원 배열의 정의와 범위 출력

In [ ]:
#2차원 배열에서의 출력
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [78]:
arr2d[2,2:]

array([11, 12])

In [124]:
arr2d[1:3,2:4] #아래 줄과 비교해서 범위 지정시 인덱스 넘버와, 원소 지정시 인덱스 넘버에 살짝 차이가 있는 것 같다. 
#정리해보면

#arr2d[1:3,2:4]
#위를 해석해보면 행의 1의 인덱스를 가지는 3을 인덱스로 가지는 행 직전까지 출력한다. 
#array([[ 5,  6,  7,  8], <-INDEX 1 
#       [ 9, 10, 11, 12]]) <- INDEX 2
#그리고 열의 2의 인덱스를 가진 열부터 4 직전(3)까지 출력한다. 
#array([[ 7,  8],
#       [11, 12]])
    

array([[ 7,  8],
       [11, 12]])

In [104]:
print(arr2d[0,0])
print(arr2d[1,3])

1
8


In [82]:
arr2d[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [86]:
arr2d[:,2] #모든 행의 2인 인덱스의 값

array([ 3,  7, 11, 15])

In [88]:
arr2d[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [109]:
arr2d[1:3,1:3]

array([[ 0,  0],
       [10, 11]])

In [100]:
arr2d[:2,1:3]=0

In [125]:
arr2d[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Boolean(bool) 타입 배열과 마스크, boolean indexing

In [137]:
names = np.array(["charles","kilho","hatoung","charles","kilho","hayoung","kilho"])
data = np.random.rand(7,4)

In [138]:
names

array(['charles', 'kilho', 'hatoung', 'charles', 'kilho', 'hayoung',
       'kilho'], 
      dtype='<U7')

In [131]:
data

array([[ 0.18878778,  0.63016904,  0.36068457,  0.67872165],
       [ 0.78985206,  0.63771048,  0.9081738 ,  0.56815519],
       [ 0.10995535,  0.49132288,  0.05969917,  0.07061317],
       [ 0.92569621,  0.22771279,  0.95565321,  0.08937835],
       [ 0.55765721,  0.45584392,  0.26258094,  0.45320534],
       [ 0.40210705,  0.84517422,  0.8343343 ,  0.32544536],
       [ 0.0881235 ,  0.23132655,  0.4266437 ,  0.75930119]])

In [139]:
names == "charles"

array([ True, False, False,  True, False, False, False], dtype=bool)

In [142]:
data[names == "charles",:] #charles 가 포함되어 있는 인덱스가 0,3 이기 때문에 해당하는 열 번호에서 True 를 반환하여 불라와진듯 하다.

array([[ 0.69798506,  0.1501275 ,  0.47282214,  0.03283901],
       [ 0.21119805,  0.48365417,  0.09203298,  0.418634  ]])

In [144]:
data[names == "kilho"]

array([[ 0.56987246,  0.07792656,  0.8123741 ,  0.54057511],
       [ 0.79756291,  0.4903992 ,  0.27678396,  0.48113613],
       [ 0.63379203,  0.30555049,  0.12687461,  0.73547649]])

In [148]:
data[(names=="kilho")|(names=="charles")]

array([[ 0.69798506,  0.1501275 ,  0.47282214,  0.03283901],
       [ 0.56987246,  0.07792656,  0.8123741 ,  0.54057511],
       [ 0.21119805,  0.48365417,  0.09203298,  0.418634  ],
       [ 0.79756291,  0.4903992 ,  0.27678396,  0.48113613],
       [ 0.63379203,  0.30555049,  0.12687461,  0.73547649]])

In [157]:
data[:,3]

array([ 0.03283901,  0.54057511,  0.96811017,  0.418634  ,  0.48113613,
        0.61330264,  0.73547649])

In [153]:
data[:,3]>0.7

array([False, False,  True, False, False, False,  True], dtype=bool)

In [155]:
data[:3] #4열값만 보기
data[:,3] < 0 #4열상에 0보다 작은 성분 조사 Q. 컴마는 왜 들어갈까?A.(행범위,열범위)에 들어간 컴마를 생각하자. 
data[data[:,3]<0,:]=0 #4열상에 0보다 작은 성분을 0으로 만들어주기

array 관련 함수(cos, sign, floor, sum, std, argmin, cumsum, cumprod 등) ppt 참고

In [162]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [164]:
np.sqrt(arr)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ])

In [166]:
np.log10(arr)

array([ 0.        ,  0.30103   ,  0.47712125,  0.60205999,  0.69897   ,
        0.77815125,  0.84509804,  0.90308999,  0.95424251])

In [169]:
x = np.random.rand(8)
y=np.random.rand(8)

In [171]:
x #다시 말하지만, numpy 의 단위값은 array 이다.

array([ 0.7149853 ,  0.89778821,  0.68598346,  0.2131998 ,  0.08262442,
        0.50801297,  0.46000677,  0.86958456])

In [173]:
y

array([ 0.18874154,  0.41585945,  0.13867178,  0.56153923,  0.99097645,
        0.70442286,  0.20569625,  0.75197328])

In [176]:
np.maximum(x,y) #각 배열의 인덱스에 해당하는 값을 비교하여 큰 값을 출력한다. 

array([ 0.7149853 ,  0.89778821,  0.68598346,  0.56153923,  0.99097645,
        0.70442286,  0.46000677,  0.86958456])

In [177]:
np.minimum(x,y) #min 과 차이를 생각한다. 

array([ 0.18874154,  0.41585945,  0.13867178,  0.2131998 ,  0.08262442,
        0.50801297,  0.20569625,  0.75197328])

In [186]:
#2차원 함수 생성
arr = np.random.rand(5,4)
arr

array([[ 0.81107573,  0.79454188,  0.1531779 ,  0.40512563],
       [ 0.35785658,  0.67560277,  0.68823027,  0.77919556],
       [ 0.33826774,  0.07437203,  0.53517433,  0.94888317],
       [ 0.57794291,  0.2527523 ,  0.87345153,  0.38198733],
       [ 0.34451758,  0.48715171,  0.36945725,  0.08434967]])

Axis 개념 (0:열기준, 1:행기준, 2: ), 영어도 기억(row, column)

In [190]:
arr.sum()

9.9331138730555857

In [192]:
arr.min() #minimum 과 차이를 생각한다. 

0.074372033430774587

In [195]:
arr.mean()

0.49665569365277928

In [196]:
#axis 값을 기준으로 합계 구하기

In [199]:
#열을 기준으로
arr.sum(axis=0)

array([ 2.42966054,  2.28442069,  2.61949128,  2.59954137])

In [201]:
arr>0.5

array([[ True,  True, False, False],
       [False,  True,  True,  True],
       [False, False,  True,  True],
       [ True, False,  True, False],
       [False, False, False, False]], dtype=bool)

In [203]:
#위 배열 중 True 의 개수를 구하기
(arr>0.5).sum()

9

Data Sorting

In [214]:
arr = np.random.rand(8)

In [209]:
arr

array([ 0.05030303,  0.26979591,  0.19977955,  0.36639358,  0.02047019,
        0.48963797,  0.74180725,  0.86714546])

In [219]:
np.sort(arr) #오름차순 정렬 Ascending

array([ 0.06692721,  0.20006613,  0.21829292,  0.26561918,  0.3123285 ,
        0.68302605,  0.75584535,  0.86507171])

In [221]:
np.sort(arr)[::-1] #내림차순 정렬 Descending

array([ 0.86507171,  0.75584535,  0.68302605,  0.3123285 ,  0.26561918,
        0.21829292,  0.20006613,  0.06692721])

In [ ]:
2차원 배열에서의 정렬

In [237]:
arr=np.random.rand(5,3)

In [280]:
arr

array([[ 0.66074698,  0.09804395,  0.76010128],
       [ 0.73561377,  0.99930704,  0.26572194],
       [ 0.7871641 ,  0.18265612,  0.40318489],
       [ 0.74189778,  0.96144286,  0.60167923],
       [ 0.06401948,  0.23060229,  0.79827299]])

In [228]:
# 모든 열을 기준으로 정렬하기

In [284]:
np.sort(arr,axis = 0)

array([[ 0.06401948,  0.09804395,  0.26572194],
       [ 0.66074698,  0.18265612,  0.40318489],
       [ 0.73561377,  0.23060229,  0.60167923],
       [ 0.74189778,  0.96144286,  0.76010128],
       [ 0.7871641 ,  0.99930704,  0.79827299]])

In [ ]:
# 첫 번째 행을 기준으로 정렬하기

In [282]:
np.sort(arr,axis = 1)

array([[ 0.09804395,  0.66074698,  0.76010128],
       [ 0.26572194,  0.73561377,  0.99930704],
       [ 0.18265612,  0.40318489,  0.7871641 ],
       [ 0.60167923,  0.74189778,  0.96144286],
       [ 0.06401948,  0.23060229,  0.79827299]])

In [286]:
large_arr= np.floor(np.random.rand(150)*1000+1)

In [287]:
#배열의 int로의 캐스팅은 다음과 같이 구현한다. 
large_arr.astype(int)

array([ 163,  879,  895,  159,  417,  407,   73,  918,  930,   88,   10,
        274,  509,  861,  237,  635,  560,  554,  757,   51,  482,  107,
        508,  945,  349,  208,  863,  803,  292,  115,    3,  150,  795,
        758,  771,  267,  663,   32,  789,  560,  703,  897,   32,  204,
        161,  539,   27,  286,  364,  302,   68,   67,   68,  835,  440,
        140,  143,  753,  763,  591,  333,  117,  562,  589,  319,  664,
        983,  957,  181,  600,   53,  139,  137,  498, 1000,  287,   53,
        488,  424,  720,  931,  903,  363,   28,  595,   37,   10,  662,
        678,  221,  631,  594,  996,   75,  916,  454,  361,  190,  560,
        680,  249,  601,  350,  365,  810,  589,  262,  758,  249,   35,
        683,  168,  534,  818,  614,  769,  476,  170,  891,   39,  947,
        938,  504,  159,  612,  331,  386,  419,  822,  303,  854,  180,
        230,  883,   74,  847,  340,  978,  933,  706,  356,  741,  929,
        228,  415,  930,  388,  925,  829,  556])

In [247]:
#오름차순 정렬
np.sort(large_arr)

array([ 0.00146803,  0.00320098,  0.00479832,  0.01103313,  0.01239382,
        0.01357768,  0.01508031,  0.0174899 ,  0.02590301,  0.03191573,
        0.03364369,  0.04632201,  0.05002554,  0.05504458,  0.07099454,
        0.07142291,  0.0771639 ,  0.08655407,  0.08708999,  0.0882829 ,
        0.09118799,  0.10777984,  0.11218482,  0.13031123,  0.13944298,
        0.1404209 ,  0.15723696,  0.15950615,  0.16716999,  0.17109814,
        0.17301522,  0.17403519,  0.17486261,  0.17583269,  0.1798842 ,
        0.18588108,  0.20564675,  0.20870185,  0.21654313,  0.22598007,
        0.23188499,  0.23530968,  0.23841007,  0.24094481,  0.2539454 ,
        0.25548947,  0.25649615,  0.27032073,  0.27333411,  0.28204157,
        0.28739169,  0.29138018,  0.30203541,  0.3054559 ,  0.31072167,
        0.31101903,  0.31170236,  0.31378441,  0.33455531,  0.33505927,
        0.34162471,  0.34193254,  0.34528611,  0.34984746,  0.36175838,
        0.38349699,  0.38473409,  0.40252003,  0.40450933,  0.41

In [248]:
#내림차순 정렬
np.sort(large_arr)[::-1]

array([ 0.99932928,  0.99925085,  0.99487059,  0.97984662,  0.97046507,
        0.96036658,  0.95827591,  0.95604349,  0.95310468,  0.94953095,
        0.94245594,  0.93149912,  0.92733776,  0.91614905,  0.88163475,
        0.88049528,  0.87240358,  0.86555318,  0.86533429,  0.86179918,
        0.8605537 ,  0.85910106,  0.85682268,  0.85567946,  0.85520592,
        0.85122387,  0.8489738 ,  0.84183128,  0.80915047,  0.80629867,
        0.79208929,  0.78476886,  0.78075906,  0.77676461,  0.76729567,
        0.76723586,  0.76133518,  0.75811197,  0.74956393,  0.73849747,
        0.73404761,  0.7313816 ,  0.72894268,  0.72616381,  0.72604044,
        0.71285599,  0.71272495,  0.70966165,  0.70077991,  0.68083174,
        0.67332918,  0.66964175,  0.66243259,  0.63680452,  0.63343745,
        0.62258869,  0.61873758,  0.60545009,  0.58584303,  0.57865574,
        0.56069462,  0.56040349,  0.54702536,  0.54068084,  0.53174345,
        0.52318762,  0.51412968,  0.50399998,  0.49655976,  0.49